<?php

namespace AppBundle\Repository\Entity\Rentable;

/**
 * ChickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChickRepository extends \Doctrine\ORM\EntityRepository
{
}
